# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dcsVyBmIa.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QToolButton, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(921, 641)
        self.groupBox_4 = QGroupBox(Dialog)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(150, 170, 261, 211))
        self.e_reads = QLineEdit(self.groupBox_4)
        self.e_reads.setObjectName(u"e_reads")
        self.e_reads.setGeometry(QRect(53, 53, 41, 23))
        font = QFont()
        font.setPointSize(10)
        self.e_reads.setFont(font)
        self.e_reads.setAlignment(Qt.AlignCenter)
        self.e_reads.setReadOnly(False)
        self.e_resets = QLineEdit(self.groupBox_4)
        self.e_resets.setObjectName(u"e_resets")
        self.e_resets.setGeometry(QRect(10, 53, 41, 23))
        self.e_resets.setFont(font)
        self.e_resets.setAlignment(Qt.AlignCenter)
        self.e_groups = QLineEdit(self.groupBox_4)
        self.e_groups.setObjectName(u"e_groups")
        self.e_groups.setGeometry(QRect(96, 53, 41, 23))
        self.e_groups.setFont(font)
        self.e_groups.setAlignment(Qt.AlignCenter)
        self.e_groups.setReadOnly(False)
        self.e_drops = QLineEdit(self.groupBox_4)
        self.e_drops.setObjectName(u"e_drops")
        self.e_drops.setGeometry(QRect(139, 53, 71, 23))
        self.e_drops.setFont(font)
        self.e_drops.setAlignment(Qt.AlignCenter)
        self.e_drops.setReadOnly(False)
        self.e_ramps = QLineEdit(self.groupBox_4)
        self.e_ramps.setObjectName(u"e_ramps")
        self.e_ramps.setGeometry(QRect(212, 53, 41, 23))
        self.e_ramps.setFont(font)
        self.e_ramps.setAlignment(Qt.AlignCenter)
        self.e_ramps.setReadOnly(False)
        self.e_fowler_number = QLineEdit(self.groupBox_4)
        self.e_fowler_number.setObjectName(u"e_fowler_number")
        self.e_fowler_number.setGeometry(QRect(125, 120, 61, 23))
        self.e_fowler_number.setAlignment(Qt.AlignCenter)
        self.e_exp_time = QLineEdit(self.groupBox_4)
        self.e_exp_time.setObjectName(u"e_exp_time")
        self.e_exp_time.setGeometry(QRect(125, 90, 61, 23))
        self.e_exp_time.setAlignment(Qt.AlignCenter)
        self.label_fowler_number = QLabel(self.groupBox_4)
        self.label_fowler_number.setObjectName(u"label_fowler_number")
        self.label_fowler_number.setGeometry(QRect(30, 120, 91, 21))
        self.label_fowler_number.setLayoutDirection(Qt.LeftToRight)
        self.label_fowler_number.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 90, 91, 21))
        self.label_13.setLayoutDirection(Qt.LeftToRight)
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 41, 21))
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(Qt.LeftToRight)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(54, 30, 41, 21))
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_groups = QLabel(self.groupBox_4)
        self.label_groups.setObjectName(u"label_groups")
        self.label_groups.setGeometry(QRect(90, 30, 51, 21))
        self.label_groups.setFont(font)
        self.label_groups.setLayoutDirection(Qt.LeftToRight)
        self.label_groups.setAlignment(Qt.AlignCenter)
        self.label_drops = QLabel(self.groupBox_4)
        self.label_drops.setObjectName(u"label_drops")
        self.label_drops.setGeometry(QRect(140, 30, 71, 21))
        self.label_drops.setFont(font)
        self.label_drops.setLayoutDirection(Qt.LeftToRight)
        self.label_drops.setAlignment(Qt.AlignCenter)
        self.label_ramps = QLabel(self.groupBox_4)
        self.label_ramps.setObjectName(u"label_ramps")
        self.label_ramps.setGeometry(QRect(210, 30, 51, 21))
        self.label_ramps.setFont(font)
        self.label_ramps.setLayoutDirection(Qt.LeftToRight)
        self.label_ramps.setAlignment(Qt.AlignCenter)
        self.radio_exp_time = QRadioButton(self.groupBox_4)
        self.radio_exp_time.setObjectName(u"radio_exp_time")
        self.radio_exp_time.setGeometry(QRect(10, 90, 21, 25))
        self.radio_fowler_number = QRadioButton(self.groupBox_4)
        self.radio_fowler_number.setObjectName(u"radio_fowler_number")
        self.radio_fowler_number.setGeometry(QRect(10, 120, 21, 25))
        self.e_repeat = QLineEdit(self.groupBox_4)
        self.e_repeat.setObjectName(u"e_repeat")
        self.e_repeat.setGeometry(QRect(200, 120, 51, 23))
        self.e_repeat.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(195, 90, 61, 21))
        self.label_16.setLayoutDirection(Qt.LeftToRight)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.line_2 = QFrame(self.groupBox_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(183, 95, 21, 45))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(430, 16, 151, 41))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(14)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_IAM = QLabel(Dialog)
        self.label_IAM.setObjectName(u"label_IAM")
        self.label_IAM.setGeometry(QRect(802, 18, 121, 41))
        font2 = QFont()
        font2.setPointSize(30)
        font2.setBold(True)
        self.label_IAM.setFont(font2)
        self.label_IAM.setLayoutDirection(Qt.LeftToRight)
        self.label_IAM.setAlignment(Qt.AlignCenter)
        self.btn_acquireramp = QPushButton(Dialog)
        self.btn_acquireramp.setObjectName(u"btn_acquireramp")
        self.btn_acquireramp.setGeometry(QRect(160, 330, 151, 41))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.btn_acquireramp.setFont(font3)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 160, 131, 221))
        font4 = QFont()
        font4.setBold(False)
        font4.setKerning(True)
        self.groupBox_3.setFont(font4)
        self.radio_UTR = QRadioButton(self.groupBox_3)
        self.radio_UTR.setObjectName(u"radio_UTR")
        self.radio_UTR.setGeometry(QRect(10, 50, 111, 21))
        self.radio_CDS = QRadioButton(self.groupBox_3)
        self.radio_CDS.setObjectName(u"radio_CDS")
        self.radio_CDS.setGeometry(QRect(10, 90, 100, 21))
        self.radio_CDSNoise = QRadioButton(self.groupBox_3)
        self.radio_CDSNoise.setObjectName(u"radio_CDSNoise")
        self.radio_CDSNoise.setGeometry(QRect(10, 130, 100, 21))
        self.radio_Fowler = QRadioButton(self.groupBox_3)
        self.radio_Fowler.setObjectName(u"radio_Fowler")
        self.radio_Fowler.setGeometry(QRect(10, 170, 100, 21))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 401, 151))
        font5 = QFont()
        font5.setBold(False)
        self.groupBox.setFont(font5)
        self.label_ver = QLabel(self.groupBox)
        self.label_ver.setObjectName(u"label_ver")
        self.label_ver.setGeometry(QRect(60, 40, 81, 21))
        self.e_timeout = QLineEdit(self.groupBox)
        self.e_timeout.setObjectName(u"e_timeout")
        self.e_timeout.setGeometry(QRect(320, 40, 71, 23))
        self.e_timeout.setAlignment(Qt.AlignCenter)
        self.btn_reset = QPushButton(self.groupBox)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(220, 100, 61, 41))
        self.btn_reset.setFont(font3)
        self.btn_initialize1 = QPushButton(self.groupBox)
        self.btn_initialize1.setObjectName(u"btn_initialize1")
        self.btn_initialize1.setGeometry(QRect(10, 100, 91, 41))
        self.btn_initialize1.setFont(font3)
        self.cmb_ouput_channels = QComboBox(self.groupBox)
        self.cmb_ouput_channels.addItem("")
        self.cmb_ouput_channels.addItem("")
        self.cmb_ouput_channels.addItem("")
        self.cmb_ouput_channels.setObjectName(u"cmb_ouput_channels")
        self.cmb_ouput_channels.setGeometry(QRect(320, 70, 71, 23))
        self.cmb_ouput_channels.setLayoutDirection(Qt.LeftToRight)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(190, 70, 121, 21))
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 41, 21))
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(160, 40, 151, 21))
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_initialize2 = QPushButton(self.groupBox)
        self.btn_initialize2.setObjectName(u"btn_initialize2")
        self.btn_initialize2.setGeometry(QRect(110, 100, 101, 41))
        self.btn_initialize2.setFont(font3)
        self.btn_get_telemetry = QPushButton(self.groupBox)
        self.btn_get_telemetry.setObjectName(u"btn_get_telemetry")
        self.btn_get_telemetry.setGeometry(QRect(290, 100, 101, 41))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        self.btn_get_telemetry.setFont(font6)
        self.groupBox_6 = QGroupBox(Dialog)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 490, 901, 141))
        self.label_18 = QLabel(self.groupBox_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 30, 181, 21))
        self.label_18.setLayoutDirection(Qt.LeftToRight)
        self.label_18.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_measured_time = QLabel(self.groupBox_6)
        self.label_measured_time.setObjectName(u"label_measured_time")
        self.label_measured_time.setGeometry(QRect(200, 57, 81, 21))
        self.label_17 = QLabel(self.groupBox_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 56, 181, 21))
        self.label_17.setLayoutDirection(Qt.LeftToRight)
        self.label_17.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_calculated_time = QLabel(self.groupBox_6)
        self.label_calculated_time.setObjectName(u"label_calculated_time")
        self.label_calculated_time.setGeometry(QRect(200, 32, 81, 21))
        self.prog_sts = QProgressBar(self.groupBox_6)
        self.prog_sts.setObjectName(u"prog_sts")
        self.prog_sts.setGeometry(QRect(10, 106, 881, 23))
        self.prog_sts.setValue(24)
        self.chk_show_fits = QCheckBox(self.groupBox_6)
        self.chk_show_fits.setObjectName(u"chk_show_fits")
        self.chk_show_fits.setGeometry(QRect(800, 33, 91, 21))
        self.label_elapsed = QLabel(self.groupBox_6)
        self.label_elapsed.setObjectName(u"label_elapsed")
        self.label_elapsed.setGeometry(QRect(200, 80, 81, 21))
        self.label_elapsed.setLayoutDirection(Qt.LeftToRight)
        self.label_elapsed.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_cur_num_3 = QLabel(self.groupBox_6)
        self.label_cur_num_3.setObjectName(u"label_cur_num_3")
        self.label_cur_num_3.setGeometry(QRect(10, 80, 181, 21))
        self.label_cur_num_3.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_cur_num = QLabel(self.groupBox_6)
        self.label_cur_num.setObjectName(u"label_cur_num")
        self.label_cur_num.setGeometry(QRect(790, 80, 101, 21))
        self.label_cur_num.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(430, 52, 481, 141))
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 59, 161, 21))
        self.label_22.setLayoutDirection(Qt.LeftToRight)
        self.label_22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_find_MACIE_reg = QToolButton(self.groupBox_2)
        self.btn_find_MACIE_reg.setObjectName(u"btn_find_MACIE_reg")
        self.btn_find_MACIE_reg.setGeometry(QRect(440, 59, 28, 23))
        self.e_MACIE_reg = QLineEdit(self.groupBox_2)
        self.e_MACIE_reg.setObjectName(u"e_MACIE_reg")
        self.e_MACIE_reg.setGeometry(QRect(180, 59, 261, 23))
        self.e_MACIE_reg.setFont(font)
        self.btn_find_config_dir = QToolButton(self.groupBox_2)
        self.btn_find_config_dir.setObjectName(u"btn_find_config_dir")
        self.btn_find_config_dir.setGeometry(QRect(440, 36, 28, 23))
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 36, 161, 21))
        self.label_23.setLayoutDirection(Qt.LeftToRight)
        self.label_23.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_config_dir = QLineEdit(self.groupBox_2)
        self.e_config_dir.setObjectName(u"e_config_dir")
        self.e_config_dir.setGeometry(QRect(180, 36, 261, 23))
        self.e_config_dir.setFont(font)
        self.btn_find_ASIC_firware = QToolButton(self.groupBox_2)
        self.btn_find_ASIC_firware.setObjectName(u"btn_find_ASIC_firware")
        self.btn_find_ASIC_firware.setGeometry(QRect(440, 82, 28, 23))
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 82, 161, 21))
        self.label_24.setLayoutDirection(Qt.LeftToRight)
        self.label_24.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_ASIC_firmware = QLineEdit(self.groupBox_2)
        self.e_ASIC_firmware.setObjectName(u"e_ASIC_firmware")
        self.e_ASIC_firmware.setGeometry(QRect(180, 82, 261, 23))
        self.e_ASIC_firmware.setFont(font)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 105, 161, 21))
        self.label_25.setLayoutDirection(Qt.LeftToRight)
        self.label_25.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_img_dir = QLineEdit(self.groupBox_2)
        self.e_img_dir.setObjectName(u"e_img_dir")
        self.e_img_dir.setGeometry(QRect(180, 105, 261, 23))
        self.e_img_dir.setFont(font)
        self.btn_find_img_dir = QToolButton(self.groupBox_2)
        self.btn_find_img_dir.setObjectName(u"btn_find_img_dir")
        self.btn_find_img_dir.setGeometry(QRect(440, 105, 28, 23))
        self.groupBox_7 = QGroupBox(Dialog)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(430, 390, 481, 91))
        self.chk_autosave = QCheckBox(self.groupBox_7)
        self.chk_autosave.setObjectName(u"chk_autosave")
        self.chk_autosave.setGeometry(QRect(10, 28, 71, 31))
        self.label_28 = QLabel(self.groupBox_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(88, 33, 71, 21))
        self.label_28.setLayoutDirection(Qt.LeftToRight)
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_29 = QLabel(self.groupBox_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(78, 57, 81, 21))
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_find_user_dir = QToolButton(self.groupBox_7)
        self.btn_find_user_dir.setObjectName(u"btn_find_user_dir")
        self.btn_find_user_dir.setGeometry(QRect(390, 34, 28, 23))
        self.label_30 = QLabel(self.groupBox_7)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(390, 57, 31, 21))
        self.label_30.setLayoutDirection(Qt.LeftToRight)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.btn_save = QToolButton(self.groupBox_7)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(420, 34, 51, 46))
        self.btn_save.setFont(font3)
        self.e_user_dir = QLineEdit(self.groupBox_7)
        self.e_user_dir.setObjectName(u"e_user_dir")
        self.e_user_dir.setGeometry(QRect(168, 34, 221, 23))
        self.e_user_dir.setFont(font)
        self.e_user_file = QLineEdit(self.groupBox_7)
        self.e_user_file.setObjectName(u"e_user_file")
        self.e_user_file.setGeometry(QRect(168, 57, 221, 23))
        self.e_user_file.setAlignment(Qt.AlignCenter)
        self.groupBox_5 = QGroupBox(Dialog)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 390, 401, 91))
        self.chk_ROI_mode = QCheckBox(self.groupBox_5)
        self.chk_ROI_mode.setObjectName(u"chk_ROI_mode")
        self.chk_ROI_mode.setGeometry(QRect(22, 42, 101, 21))
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(330, 30, 51, 21))
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.e_x_stop = QLineEdit(self.groupBox_5)
        self.e_x_stop.setObjectName(u"e_x_stop")
        self.e_x_stop.setGeometry(QRect(210, 57, 51, 23))
        self.e_x_stop.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(270, 30, 51, 21))
        self.label_11.setLayoutDirection(Qt.LeftToRight)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(210, 30, 51, 21))
        self.label_12.setLayoutDirection(Qt.LeftToRight)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.groupBox_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 30, 51, 21))
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.e_y_stop = QLineEdit(self.groupBox_5)
        self.e_y_stop.setObjectName(u"e_y_stop")
        self.e_y_stop.setGeometry(QRect(330, 57, 51, 23))
        self.e_y_stop.setAlignment(Qt.AlignCenter)
        self.e_y_start = QLineEdit(self.groupBox_5)
        self.e_y_start.setObjectName(u"e_y_start")
        self.e_y_start.setGeometry(QRect(270, 57, 51, 23))
        self.e_y_start.setAlignment(Qt.AlignCenter)
        self.e_x_start = QLineEdit(self.groupBox_5)
        self.e_x_start.setObjectName(u"e_x_start")
        self.e_x_start.setGeometry(QRect(150, 57, 51, 23))
        self.e_x_start.setAlignment(Qt.AlignCenter)
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(410, 26, 21, 451))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.btn_stop = QPushButton(Dialog)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(320, 330, 81, 41))
        self.btn_stop.setFont(font3)
        self.groupBox_9 = QGroupBox(Dialog)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(430, 197, 481, 191))
        self.e_addr_Vreset = QLineEdit(self.groupBox_9)
        self.e_addr_Vreset.setObjectName(u"e_addr_Vreset")
        self.e_addr_Vreset.setGeometry(QRect(130, 65, 51, 23))
        self.e_addr_Vreset.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_addr_Vreset.setReadOnly(True)
        self.e_addr_Dsub = QLineEdit(self.groupBox_9)
        self.e_addr_Dsub.setObjectName(u"e_addr_Dsub")
        self.e_addr_Dsub.setGeometry(QRect(130, 88, 51, 23))
        self.e_addr_Dsub.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_addr_Dsub.setReadOnly(True)
        self.e_addr_Vbiasgate = QLineEdit(self.groupBox_9)
        self.e_addr_Vbiasgate.setObjectName(u"e_addr_Vbiasgate")
        self.e_addr_Vbiasgate.setGeometry(QRect(130, 111, 51, 23))
        self.e_addr_Vbiasgate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_addr_Vbiasgate.setReadOnly(True)
        self.e_addr_Vrefmain = QLineEdit(self.groupBox_9)
        self.e_addr_Vrefmain.setObjectName(u"e_addr_Vrefmain")
        self.e_addr_Vrefmain.setGeometry(QRect(130, 134, 51, 23))
        self.e_addr_Vrefmain.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_addr_Vrefmain.setReadOnly(True)
        self.label_5 = QLabel(self.groupBox_9)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(128, 51, 56, 12))
        self.label_6 = QLabel(self.groupBox_9)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 65, 101, 20))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(self.groupBox_9)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 88, 101, 20))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_8 = QLabel(self.groupBox_9)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 111, 101, 20))
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(self.groupBox_9)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 134, 101, 20))
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_write_Dsub = QLineEdit(self.groupBox_9)
        self.e_write_Dsub.setObjectName(u"e_write_Dsub")
        self.e_write_Dsub.setGeometry(QRect(190, 88, 51, 23))
        self.e_write_Dsub.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_write_Vbiasgate = QLineEdit(self.groupBox_9)
        self.e_write_Vbiasgate.setObjectName(u"e_write_Vbiasgate")
        self.e_write_Vbiasgate.setGeometry(QRect(190, 111, 51, 23))
        self.e_write_Vbiasgate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_write_Vrefmain = QLineEdit(self.groupBox_9)
        self.e_write_Vrefmain.setObjectName(u"e_write_Vrefmain")
        self.e_write_Vrefmain.setGeometry(QRect(190, 134, 51, 23))
        self.e_write_Vrefmain.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_write_Vreset = QLineEdit(self.groupBox_9)
        self.e_write_Vreset.setObjectName(u"e_write_Vreset")
        self.e_write_Vreset.setGeometry(QRect(190, 65, 51, 23))
        self.e_write_Vreset.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_Dsub = QLineEdit(self.groupBox_9)
        self.e_read_Dsub.setObjectName(u"e_read_Dsub")
        self.e_read_Dsub.setGeometry(QRect(250, 88, 51, 23))
        self.e_read_Dsub.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_Dsub.setReadOnly(True)
        self.e_read_Vbiasgate = QLineEdit(self.groupBox_9)
        self.e_read_Vbiasgate.setObjectName(u"e_read_Vbiasgate")
        self.e_read_Vbiasgate.setGeometry(QRect(250, 111, 51, 23))
        self.e_read_Vbiasgate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_Vbiasgate.setReadOnly(True)
        self.e_read_Vrefmain = QLineEdit(self.groupBox_9)
        self.e_read_Vrefmain.setObjectName(u"e_read_Vrefmain")
        self.e_read_Vrefmain.setGeometry(QRect(250, 134, 51, 23))
        self.e_read_Vrefmain.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_Vrefmain.setReadOnly(True)
        self.e_read_Vreset = QLineEdit(self.groupBox_9)
        self.e_read_Vreset.setObjectName(u"e_read_Vreset")
        self.e_read_Vreset.setGeometry(QRect(250, 65, 51, 23))
        self.e_read_Vreset.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_Vreset.setReadOnly(True)
        self.label_15 = QLabel(self.groupBox_9)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(194, 51, 56, 12))
        self.label_26 = QLabel(self.groupBox_9)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(254, 51, 56, 12))
        self.btn_write_Vreset = QPushButton(self.groupBox_9)
        self.btn_write_Vreset.setObjectName(u"btn_write_Vreset")
        self.btn_write_Vreset.setGeometry(QRect(310, 65, 71, 23))
        self.btn_write_Vreset.setFont(font3)
        self.btn_read_Vreset = QPushButton(self.groupBox_9)
        self.btn_read_Vreset.setObjectName(u"btn_read_Vreset")
        self.btn_read_Vreset.setGeometry(QRect(390, 65, 71, 23))
        self.btn_read_Vreset.setFont(font3)
        self.btn_read_Dsub = QPushButton(self.groupBox_9)
        self.btn_read_Dsub.setObjectName(u"btn_read_Dsub")
        self.btn_read_Dsub.setGeometry(QRect(390, 88, 71, 23))
        self.btn_read_Dsub.setFont(font3)
        self.btn_write_Dsub = QPushButton(self.groupBox_9)
        self.btn_write_Dsub.setObjectName(u"btn_write_Dsub")
        self.btn_write_Dsub.setGeometry(QRect(310, 88, 71, 23))
        self.btn_write_Dsub.setFont(font3)
        self.btn_read_Vbiasgate = QPushButton(self.groupBox_9)
        self.btn_read_Vbiasgate.setObjectName(u"btn_read_Vbiasgate")
        self.btn_read_Vbiasgate.setGeometry(QRect(390, 111, 71, 23))
        self.btn_read_Vbiasgate.setFont(font3)
        self.btn_write_Vbiasgate = QPushButton(self.groupBox_9)
        self.btn_write_Vbiasgate.setObjectName(u"btn_write_Vbiasgate")
        self.btn_write_Vbiasgate.setGeometry(QRect(310, 111, 71, 23))
        self.btn_write_Vbiasgate.setFont(font3)
        self.btn_read_Vrefmain = QPushButton(self.groupBox_9)
        self.btn_read_Vrefmain.setObjectName(u"btn_read_Vrefmain")
        self.btn_read_Vrefmain.setGeometry(QRect(390, 134, 71, 23))
        self.btn_read_Vrefmain.setFont(font3)
        self.btn_write_Vrefmain = QPushButton(self.groupBox_9)
        self.btn_write_Vrefmain.setObjectName(u"btn_write_Vrefmain")
        self.btn_write_Vrefmain.setGeometry(QRect(310, 134, 71, 23))
        self.btn_write_Vrefmain.setFont(font3)
        self.btn_write_input = QPushButton(self.groupBox_9)
        self.btn_write_input.setObjectName(u"btn_write_input")
        self.btn_write_input.setGeometry(QRect(310, 157, 71, 23))
        self.btn_write_input.setFont(font3)
        self.e_read_input = QLineEdit(self.groupBox_9)
        self.e_read_input.setObjectName(u"e_read_input")
        self.e_read_input.setGeometry(QRect(250, 157, 51, 23))
        font7 = QFont()
        font7.setPointSize(1)
        self.e_read_input.setFont(font7)
        self.e_read_input.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_read_input.setReadOnly(True)
        self.e_addr_input = QLineEdit(self.groupBox_9)
        self.e_addr_input.setObjectName(u"e_addr_input")
        self.e_addr_input.setGeometry(QRect(130, 157, 51, 23))
        self.e_addr_input.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_27 = QLabel(self.groupBox_9)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 157, 101, 20))
        self.label_27.setLayoutDirection(Qt.LeftToRight)
        self.label_27.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_write_input = QLineEdit(self.groupBox_9)
        self.e_write_input.setObjectName(u"e_write_input")
        self.e_write_input.setGeometry(QRect(190, 157, 51, 23))
        self.e_write_input.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_read_input = QPushButton(self.groupBox_9)
        self.btn_read_input.setObjectName(u"btn_read_input")
        self.btn_read_input.setGeometry(QRect(390, 157, 71, 23))
        self.btn_read_input.setFont(font3)
        self.btn_ASIC_load = QPushButton(self.groupBox_9)
        self.btn_ASIC_load.setObjectName(u"btn_ASIC_load")
        self.btn_ASIC_load.setGeometry(QRect(310, 33, 151, 31))
        self.btn_ASIC_load.setFont(font3)
        QWidget.setTabOrder(self.e_timeout, self.cmb_ouput_channels)
        QWidget.setTabOrder(self.cmb_ouput_channels, self.btn_initialize1)
        QWidget.setTabOrder(self.btn_initialize1, self.btn_initialize2)
        QWidget.setTabOrder(self.btn_initialize2, self.btn_reset)
        QWidget.setTabOrder(self.btn_reset, self.btn_get_telemetry)
        QWidget.setTabOrder(self.btn_get_telemetry, self.radio_UTR)
        QWidget.setTabOrder(self.radio_UTR, self.radio_CDS)
        QWidget.setTabOrder(self.radio_CDS, self.radio_CDSNoise)
        QWidget.setTabOrder(self.radio_CDSNoise, self.radio_Fowler)
        QWidget.setTabOrder(self.radio_Fowler, self.e_resets)
        QWidget.setTabOrder(self.e_resets, self.e_reads)
        QWidget.setTabOrder(self.e_reads, self.e_groups)
        QWidget.setTabOrder(self.e_groups, self.e_drops)
        QWidget.setTabOrder(self.e_drops, self.e_ramps)
        QWidget.setTabOrder(self.e_ramps, self.radio_exp_time)
        QWidget.setTabOrder(self.radio_exp_time, self.e_exp_time)
        QWidget.setTabOrder(self.e_exp_time, self.radio_fowler_number)
        QWidget.setTabOrder(self.radio_fowler_number, self.e_fowler_number)
        QWidget.setTabOrder(self.e_fowler_number, self.e_repeat)
        QWidget.setTabOrder(self.e_repeat, self.btn_acquireramp)
        QWidget.setTabOrder(self.btn_acquireramp, self.btn_stop)
        QWidget.setTabOrder(self.btn_stop, self.chk_ROI_mode)
        QWidget.setTabOrder(self.chk_ROI_mode, self.e_x_start)
        QWidget.setTabOrder(self.e_x_start, self.e_x_stop)
        QWidget.setTabOrder(self.e_x_stop, self.e_y_start)
        QWidget.setTabOrder(self.e_y_start, self.e_y_stop)
        QWidget.setTabOrder(self.e_y_stop, self.e_config_dir)
        QWidget.setTabOrder(self.e_config_dir, self.btn_find_config_dir)
        QWidget.setTabOrder(self.btn_find_config_dir, self.e_MACIE_reg)
        QWidget.setTabOrder(self.e_MACIE_reg, self.btn_find_MACIE_reg)
        QWidget.setTabOrder(self.btn_find_MACIE_reg, self.e_ASIC_firmware)
        QWidget.setTabOrder(self.e_ASIC_firmware, self.btn_find_ASIC_firware)
        QWidget.setTabOrder(self.btn_find_ASIC_firware, self.e_img_dir)
        QWidget.setTabOrder(self.e_img_dir, self.btn_find_img_dir)
        QWidget.setTabOrder(self.btn_find_img_dir, self.btn_ASIC_load)
        QWidget.setTabOrder(self.btn_ASIC_load, self.e_addr_Vreset)
        QWidget.setTabOrder(self.e_addr_Vreset, self.e_write_Vreset)
        QWidget.setTabOrder(self.e_write_Vreset, self.e_read_Vreset)
        QWidget.setTabOrder(self.e_read_Vreset, self.btn_write_Vreset)
        QWidget.setTabOrder(self.btn_write_Vreset, self.btn_read_Vreset)
        QWidget.setTabOrder(self.btn_read_Vreset, self.e_addr_Dsub)
        QWidget.setTabOrder(self.e_addr_Dsub, self.e_write_Dsub)
        QWidget.setTabOrder(self.e_write_Dsub, self.e_read_Dsub)
        QWidget.setTabOrder(self.e_read_Dsub, self.btn_write_Dsub)
        QWidget.setTabOrder(self.btn_write_Dsub, self.btn_read_Dsub)
        QWidget.setTabOrder(self.btn_read_Dsub, self.e_addr_Vbiasgate)
        QWidget.setTabOrder(self.e_addr_Vbiasgate, self.e_write_Vbiasgate)
        QWidget.setTabOrder(self.e_write_Vbiasgate, self.e_read_Vbiasgate)
        QWidget.setTabOrder(self.e_read_Vbiasgate, self.btn_write_Vbiasgate)
        QWidget.setTabOrder(self.btn_write_Vbiasgate, self.btn_read_Vbiasgate)
        QWidget.setTabOrder(self.btn_read_Vbiasgate, self.e_addr_Vrefmain)
        QWidget.setTabOrder(self.e_addr_Vrefmain, self.e_write_Vrefmain)
        QWidget.setTabOrder(self.e_write_Vrefmain, self.e_read_Vrefmain)
        QWidget.setTabOrder(self.e_read_Vrefmain, self.btn_write_Vrefmain)
        QWidget.setTabOrder(self.btn_write_Vrefmain, self.btn_read_Vrefmain)
        QWidget.setTabOrder(self.btn_read_Vrefmain, self.e_addr_input)
        QWidget.setTabOrder(self.e_addr_input, self.e_write_input)
        QWidget.setTabOrder(self.e_write_input, self.e_read_input)
        QWidget.setTabOrder(self.e_read_input, self.btn_write_input)
        QWidget.setTabOrder(self.btn_write_input, self.btn_read_input)
        QWidget.setTabOrder(self.btn_read_input, self.chk_autosave)
        QWidget.setTabOrder(self.chk_autosave, self.e_user_dir)
        QWidget.setTabOrder(self.e_user_dir, self.btn_find_user_dir)
        QWidget.setTabOrder(self.btn_find_user_dir, self.btn_save)
        QWidget.setTabOrder(self.btn_save, self.e_user_file)
        QWidget.setTabOrder(self.e_user_file, self.chk_show_fits)

        self.retranslateUi(Dialog)

        self.btn_ASIC_load.setDefault(True)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Sampling Parameters", None))
        self.e_reads.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_resets.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_groups.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_drops.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_ramps.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_fowler_number.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_exp_time.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_fowler_number.setText(QCoreApplication.translate("Dialog", u"N. Fowler:", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Exp. Time (s):", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Resets", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Reads", None))
        self.label_groups.setText(QCoreApplication.translate("Dialog", u"Groups", None))
        self.label_drops.setText(QCoreApplication.translate("Dialog", u"Drops", None))
        self.label_ramps.setText(QCoreApplication.translate("Dialog", u"Ramps", None))
        self.radio_exp_time.setText("")
        self.radio_fowler_number.setText("")
        self.e_repeat.setText(QCoreApplication.translate("Dialog", u"1", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Repeat", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Manual Mode", None))
        self.label_IAM.setText(QCoreApplication.translate("Dialog", u"DCSS", None))
        self.btn_acquireramp.setText(QCoreApplication.translate("Dialog", u"AcquireRamp", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Sampling Mode", None))
        self.radio_UTR.setText(QCoreApplication.translate("Dialog", u"Up-The-Ramp", None))
        self.radio_CDS.setText(QCoreApplication.translate("Dialog", u"CDS", None))
        self.radio_CDSNoise.setText(QCoreApplication.translate("Dialog", u"CDS Noise", None))
        self.radio_Fowler.setText(QCoreApplication.translate("Dialog", u"Fowler", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Initializing", None))
        self.label_ver.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.e_timeout.setText(QCoreApplication.translate("Dialog", u"200", None))
        self.btn_reset.setText(QCoreApplication.translate("Dialog", u"Reset", None))
        self.btn_initialize1.setText(QCoreApplication.translate("Dialog", u"Initialize1", None))
        self.cmb_ouput_channels.setItemText(0, QCoreApplication.translate("Dialog", u"1", None))
        self.cmb_ouput_channels.setItemText(1, QCoreApplication.translate("Dialog", u"4", None))
        self.cmb_ouput_channels.setItemText(2, QCoreApplication.translate("Dialog", u"32", None))

        self.label_4.setText(QCoreApplication.translate("Dialog", u"Output channels:", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Ver.", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"SetGigeTimeout (ms):", None))
        self.btn_initialize2.setText(QCoreApplication.translate("Dialog", u"Initialize2", None))
        self.btn_get_telemetry.setText(QCoreApplication.translate("Dialog", u"GetTelemetry", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Dialog", u"Acquiring Status", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Calculated waiting time (s):", None))
        self.label_measured_time.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Measured waiting time (s):", None))
        self.label_calculated_time.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.chk_show_fits.setText(QCoreApplication.translate("Dialog", u"Show FITS", None))
        self.label_elapsed.setText(QCoreApplication.translate("Dialog", u"0.0", None))
        self.label_cur_num_3.setText(QCoreApplication.translate("Dialog", u"Elapsed (s):", None))
        self.label_cur_num.setText(QCoreApplication.translate("Dialog", u"1 / 1", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Configuration Files", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"MACIE Register (mrf):", None))
        self.btn_find_MACIE_reg.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.e_MACIE_reg.setText(QCoreApplication.translate("Dialog", u"MACIE_Registers_Slow.mrf", None))
        self.btn_find_config_dir.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Configuration Directory:", None))
        self.e_config_dir.setText(QCoreApplication.translate("Dialog", u"/home/dcs/macie_v5.2_centos/LoadFiles", None))
        self.btn_find_ASIC_firware.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"ASIC Firmware (mcd):", None))
        self.e_ASIC_firmware.setText(QCoreApplication.translate("Dialog", u"HxRG_Main.mcd", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Image Directory:", None))
        self.e_img_dir.setText(QCoreApplication.translate("Dialog", u"/DCS/Data", None))
        self.btn_find_img_dir.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Dialog", u"Save As", None))
        self.chk_autosave.setText(QCoreApplication.translate("Dialog", u"Save As", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Directory:", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Filename:", None))
        self.btn_find_user_dir.setText(QCoreApplication.translate("Dialog", u"...", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u".fits", None))
        self.btn_save.setText(QCoreApplication.translate("Dialog", u"save", None))
        self.e_user_dir.setText(QCoreApplication.translate("Dialog", u"/home/dcs", None))
        self.e_user_file.setText(QCoreApplication.translate("Dialog", u"name", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Dialog", u"Window Mode", None))
        self.chk_ROI_mode.setText(QCoreApplication.translate("Dialog", u"ROI Mode", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Y stop", None))
        self.e_x_stop.setText(QCoreApplication.translate("Dialog", u"2047", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Y start", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"X stop", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"X start", None))
        self.e_y_stop.setText(QCoreApplication.translate("Dialog", u"2047", None))
        self.e_y_start.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.e_x_start.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.btn_stop.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("Dialog", u"Single Register Read - Write (ASIC)", None))
        self.e_addr_Vreset.setText(QCoreApplication.translate("Dialog", u"6000", None))
        self.e_addr_Dsub.setText(QCoreApplication.translate("Dialog", u"6002", None))
        self.e_addr_Vbiasgate.setText(QCoreApplication.translate("Dialog", u"6004", None))
        self.e_addr_Vrefmain.setText(QCoreApplication.translate("Dialog", u"602c", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Addr (h)", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Vreset:", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Dsub:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"VBiasGate:", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"VRef.Main:", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Val (W)", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"Val (R)", None))
        self.btn_write_Vreset.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.btn_read_Vreset.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.btn_read_Dsub.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.btn_write_Dsub.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.btn_read_Vbiasgate.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.btn_write_Vbiasgate.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.btn_read_Vrefmain.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.btn_write_Vrefmain.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.btn_write_input.setText(QCoreApplication.translate("Dialog", u"write", None))
        self.e_addr_input.setText("")
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Address:", None))
        self.btn_read_input.setText(QCoreApplication.translate("Dialog", u"read", None))
        self.btn_ASIC_load.setText(QCoreApplication.translate("Dialog", u"ASIC Load", None))
    # retranslateUi

